// Auto-generated by export_sauron.py — do not edit by hand.
window.SAURON_DATA = {
  "product": "Sauron",
  "config": {
    "window": "2Y",
    "rebalance": "1M",
    "hold_days": 21,
    "growth_mix": 0.75,
    "n": 10,
    "cost_bps": 10.0
  },
  "as_of": "2026-04-17",
  "book_date": "2026-04-17",
  "book": [
    {
      "ticker": "AAOI",
      "name": "Applied Optoelectronics Inc.",
      "sector": "Information Technology",
      "weight": 0.1,
      "accel": 3.185735119850062
    },
    {
      "ticker": "CAR",
      "name": "Avis Budget Group Inc.",
      "sector": "Industrials",
      "weight": 0.1,
      "accel": 3.1461628299254705
    },
    {
      "ticker": "UI",
      "name": "Ubiquiti Inc.",
      "sector": "Information Technology",
      "weight": 0.1,
      "accel": 1.2225895307671566
    },
    {
      "ticker": "MOD",
      "name": "Modine Manufacturing Company",
      "sector": "Consumer Discretionary",
      "weight": 0.1,
      "accel": 1.0346491551985464
    },
    {
      "ticker": "VRT",
      "name": "Vertiv Holdings LLC",
      "sector": "Information Technology",
      "weight": 0.1,
      "accel": 0.8254881773070709
    },
    {
      "ticker": "NIO",
      "name": "Nio Inc",
      "sector": "Consumer Discretionary",
      "weight": 0.1,
      "accel": 0.7916309150770154
    },
    {
      "ticker": "MARA",
      "name": "MARA Holdings Inc.",
      "sector": "Industrials",
      "weight": 0.1,
      "accel": 0.6214551299477442
    },
    {
      "ticker": "SM",
      "name": "SM Energy Company",
      "sector": "Energy",
      "weight": 0.1,
      "accel": 0.5820115274649837
    },
    {
      "ticker": "VG",
      "name": "Venture Global Inc.",
      "sector": "Utilities",
      "weight": 0.1,
      "accel": 0.5683683266013171
    },
    {
      "ticker": "CRWV",
      "name": "CoreWeave Inc.",
      "sector": "Industrials",
      "weight": 0.1,
      "accel": 0.5475234810910012
    }
  ],
  "performance": {
    "cagr": 0.49752668482463336,
    "sharpe": 1.6543119078362967,
    "max_drawdown": -0.12928317784408494,
    "total_return": 1.242586171761857
  },
  "curve": {
    "dates": [
      "2024-05-13",
      "2024-06-12",
      "2024-07-15",
      "2024-08-13",
      "2024-09-12",
      "2024-10-11",
      "2024-11-11",
      "2024-12-11",
      "2025-01-14",
      "2025-02-13",
      "2025-03-17",
      "2025-04-15",
      "2025-05-15",
      "2025-06-16",
      "2025-07-17",
      "2025-08-15",
      "2025-09-16",
      "2025-10-15",
      "2025-11-13",
      "2025-12-15",
      "2026-01-15",
      "2026-02-17",
      "2026-03-18",
      "2026-04-17"
    ],
    "model": [
      0.9819,
      1.0751,
      0.9418,
      0.9361,
      1.011,
      1.1431,
      1.2892,
      1.2348,
      1.3335,
      1.2136,
      1.1958,
      1.2062,
      1.2309,
      1.4437,
      1.4343,
      1.6778,
      1.8604,
      1.8065,
      1.98,
      2.1373,
      2.271,
      2.2887,
      2.3944,
      2.2426
    ],
    "sp500": [
      1.0398,
      1.0814,
      1.0443,
      1.0769,
      1.1204,
      1.1571,
      1.1748,
      1.1295,
      1.183,
      1.0998,
      1.0468,
      1.1489,
      1.1731,
      1.2255,
      1.2563,
      1.2887,
      1.3023,
      1.316,
      1.3335,
      1.3597,
      1.3412,
      1.3001,
      1.3996,
      1.4552
    ]
  },
  "windows": [
    {
      "w": "1Y",
      "cagr": 0.8592233143435741,
      "sharpe": 2.7011962578666067,
      "dd": -0.0634225138776987,
      "sp_cagr": 0.26664095463222526,
      "excess": 0.5925823597113489
    },
    {
      "w": "2Y",
      "cagr": 0.49752668482463336,
      "sharpe": 1.6543119078362967,
      "dd": -0.12928317784408494,
      "sp_cagr": 0.20631352824917193,
      "excess": 0.29121315657546143
    },
    {
      "w": "5Y",
      "cagr": 0.1811656434624931,
      "sharpe": 0.7347365172162031,
      "dd": -0.3667250810930457,
      "sp_cagr": 0.13909402949217742,
      "excess": 0.04207161397031567
    },
    {
      "w": "MAX",
      "cagr": 0.14315776405584768,
      "sharpe": 0.7102042917474017,
      "dd": -0.3667250810930456,
      "sp_cagr": 0.11214716581036321,
      "excess": 0.031010598245484466
    }
  ],
  "generated_at": "2026-06-17T17:00:49Z",
  "disclaimer": "Backtest, net of ~10bps costs. Not a forecast or investment advice."
};
